# Generated by Django 4.0.2 on 2022-03-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quality', models.CharField(max_length=10)),
                ('video_url', models.CharField(max_length=50)),
            ],
        ),
    ]
